# Generated by Django 4.2 on 2023-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Mobile Phones', 'Mobile Phones')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(),
        ),
    ]
